// Generated by CoffeeScript 1.9.3
window.CONFIG = {
  all_char_num: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16].concat([32, 64]),
  upper_char_num: [0, 1, 2, 3, 4, 5, 6, 7, 8],
  lower_char_num: [0, 1, 2, 3, 4, 5, 6, 7, 8],
  int_char_num: [0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_char_num: [0, 1, 2, 3, 4, 5, 6, 7, 8],
  sp_char_set: [['_'], ['_[]()'], ['_[]()!?@:;,.+-*/']]
};

$().ready(function() {
  var content, i, id, len, results, select, v, val;
  results = [];
  for (id in CONFIG) {
    content = CONFIG[id];
    select = $('#' + id);
    select.html('');
    for (i = 0, len = content.length; i < len; i++) {
      v = content[i];
      select.append($('<option>').val(v).html(v));
    }
    select.on('change', function() {
      console.log('cookie [' + $(this).attr('id') + '] ' + $(this).val());
      return $.cookie($(this).attr('id'), $(this).val(), {
        expires: 365 * 100
      });
    });
    val = $.cookie(id);
    if (val !== null) {
      results.push(select.val(val));
    } else {
      results.push(void 0);
    }
  }
  return results;
});
